### ISSUE TITLE
Single-cell RNA-seq workshop (Oct 2021) - ideas to consider for next workshop

### ISSUE THREAD

**Issue by ayushi-agrawal-gladstone** [gladstone-institutes/Bioinformatics-Workshops#1]
Hi All, 

Looking over the [feedback ](https://www.dropbox.com/s/pq8arogdn2w3xk5/10_22_21_Single_Cell_RNA.pdf?dl=0)for the single-cell RNA-seq workshop, I had a few ideas that I thought we could consider for the next time we do this workshop. I added this GitHub issue to stash these ideas in one place. Here are a few ideas from me:

1. Provide deep-dive materials, like papers and math details -- probably after the workshop?
2. Add scATAC-seq?  As workshop slides or extra references.

If you have some ideas in mind, please feel free to add to the list by commenting/replying on this issue.

Thanks,
Ayushi

**Comment by AlexanderPico** [comment]
https://docs.google.com/document/d/1v7amOkxXTQLsuWLeSVxD6dLGydxgiv98VyFPbP9Xygk/edit

**Comment by ayushi-agrawal-gladstone** [comment]
Incorporated these ideas starting the Oct, 2023 workshop. Closing the issue.
