### ISSUE TITLE
Pathway Analysis workshop updates

### ISSUE THREAD

**Issue by AlexanderPico** [gladstone-institutes/Bioinformatics-Workshops#13]
Based on the Oct 31 session, the following updates should be considered:

- [x] There was confusion about where in the analysis pipeline we were focusing. We could have a slide near the beginning illustrating an analysis pipeline and then clearly state that we are not covering prior steps. Others might already have a pipeline slide. Ask around. -> Added slide in the beginning: https://docs.google.com/presentation/d/1Qheb-TiSAXh0P1Wsu-3GYi-TY_5ubTJmlAWEAipgWig/edit#slide=id.g2a00b9273dc_0_7.
- [x] In "Exploratory Analysis" slide we could contrast with "Confirmatory Analysis" to help define the terms. Might also use the term "Recommender system, like Netflix" to help give an intuitive sense. -> Added slide here: https://docs.google.com/presentation/d/1Qheb-TiSAXh0P1Wsu-3GYi-TY_5ubTJmlAWEAipgWig/edit#slide=id.g2a00b9273dc_0_39 (I consider this a draft)
- [ ] We miss one of the key strengths of pathway analysis: detecting biological effects even if individual gene changes are not statistically significant. A slide with a data overlay would probably make this clear.
- [x] Add mSigDB and Cytoscape to lists of other commonly used tools
- [x] Mention that ORA thresholds can be set to include up, down, or both (i.e., ignoring sign). Each of these three sets would be valid to test; each would be interpreted slightly differently.
- [x] The session didn't have a clear end. Could have a slide called "Wrap-up" where you invite folks to continue with hands-on exercises, their own data, etc. or can take the survey and leave early. -> moved slides around, and updated [this slide](https://docs.google.com/presentation/d/1Qheb-TiSAXh0P1Wsu-3GYi-TY_5ubTJmlAWEAipgWig/edit#slide=id.p15).

**Comment by khanspers** [comment]
Additional points of improvement:

1. We use the term "pre-filtering" to refer to what the researcher does to create input lists. Revise this to use a different word since its confusing.
2. p-value vs FDR adjusted p-value: A common question is related to which p-value to use for filtering the data to produce lists. Add a slide to address this, aka use the regular p-value since the enrichment methods also calculates adjusted p-value
3. Add better explanation of rank score calculation in the slide.

**Comment by khanspers** [comment]
https://baderlab.github.io/CBW_Pathways_2020/lectures/Pathways_2020_Module2_ORA_veronique.pdf

**Comment by khanspers** [comment]
**p-value vs FDR adjusted p-value**: Added slide https://docs.google.com/presentation/d/1Qheb-TiSAXh0P1Wsu-3GYi-TY_5ubTJmlAWEAipgWig/edit#slide=id.g2a00b9273dc_0_49

**Comment by khanspers** [comment]
For the last point: "We miss one of the key strengths of pathway analysis: detecting biological effects even if individual gene changes are not statistically significant. A slide with a data overlay would probably make this clear." 

Here's what I think we meant by this: In the below figure, which shows a pathway from GSEA results of an autism study, log2FC visualized as node color, many of the genes have modest changes; GSEA will find pathway-level effects even if the individual genes involved have small changes. @AlexanderPico: If you agree I will add a new silde with this

<img width="1165" alt="Screen Shot 2024-03-28 at 12 18 47 PM" src="https://github.com/gladstone-institutes/Bioinformatics-Workshops/assets/1442197/dc2fa8d5-a30b-4e4d-ac5f-0b01a649ed12">
