### ISSUE TITLE
Pathway Analysis workshop updates 2024

### ISSUE THREAD

**Issue by AlexanderPico** [gladstone-institutes/Bioinformatics-Workshops#17]
- [x] Add column to comparison table for number of libraries
- [x] Add DAVID to list (moved MSigDB to "database-specific" bullet point since we describe it in terms of a data source more than the actual tool)
- [x] Test webtools and document bugs before next workshop (e.g., WPIDs that fail to view in webgestalt and IEA)

**Comment by khanspers** [comment]
- [ ] Add single-cell RNA seq example as input data type (marker list / cell-type specific DEGs)
- [ ] Add to Interactive Enrichment Analysis demo: supported input list types (see help), can add gmt files from Enrichr (as custom database?)
