### ISSUE TITLE
Bulk RNA-seq workshop (July 2022) - ideas to consider for next workshop 

### ISSUE THREAD

**Issue by ayushi-agrawal-gladstone** [gladstone-institutes/Bioinformatics-Workshops#2]
1. Have 30 min at the starting of session 1 to help the participants with getting the Docker container running and logging into wynton.
2. Share the commands for logging into wynton and starting docker (e.g. docker images or docker version commands) before hand as per-workshop instructions
3. Keep session 1 for concepts by Michela and session 2 for demo with Ayushi
4. Let Wynton team know in advance that they may receive a lot of new account requests
5. Share email about creating wynton account at least 1.5 weeks before the workshop.
6. Windows commands for the corresponding mac/linux commands
7. Pre-workshop instructions to try basic commands (e.g. ls, cat, cd, etc)

**Comment by ayushi-agrawal-gladstone** [comment]
@MichelaTr Please feel free to add to the list

**Comment by MichelaTr** [comment]
1. Have 30 min at the starting of session 1 to help the participants with getting the Docker container running and logging into wynton.
2. Share the commands for logging into wynton and starting docker (e.g. docker images or docker version commands) before hand as per-workshop instructions
3. Keep session 1 for concepts by Michela and session 2 for demo with Ayushi
4. Or have 3 session of 3 hours, 2 hours, 2 hours. 
- Day 1: 30 minutes (point1), session 1 concepts + fastaqc
- Day 2 morning: session2 concepts only from trimming to the end (make some concepts more easy)
- Day 2 afternoon: session 3 demo only
6. Let Wynton team know in advance that they may receive a lot of new account requests
7. Share email about creating wynton account at least 2 weeks before the workshop.
8. Share demo commands for wynton with the email point 6

**Comment by MichelaTr** [comment]
Thank you very much.
I added my comments, see what you think :)
We can discuss during the lab meeting this week if I am able to join (I
will let you know) or in 2 weeks!

Michela

**Comment by ayushi-agrawal-gladstone** [comment]
I like the point #4 you added. Let's discuss more in the lab meeting as you suggested. :)

**Comment by MichelaTr** [comment]
Or have 3 session of 2 hours, 2.5 hours, 2.5 hours.
Day 1: concepts only
Day 2 morning: session2 demo only  on wynton
Day 2 afternoon: session 3 demo only with docker

**Comment by MichelaTr** [comment]
Int his way, less students and people that wants to know both they can join both

**Comment by ayushi-agrawal-gladstone** [comment]
That sounds even better. In addition to the advantage you mentioned, this way participants will have the wholistic idea of the steps in the pipeline from day1 and would be able to understand better the demo.

**Comment by ayushi-agrawal-gladstone** [comment]
@AlexanderPico We will appreciate your input on these points.

**Comment by AlexanderPico** [comment]
oooh, yes. I like this idea! Let's give it try next time and see how it goes.

**Comment by ayushi-agrawal-gladstone** [comment]
@AlexanderPico @reubenthomas Michela and I had a discussion about the format of the workshop. We both think that keeping the demo using only the docker container (no wynton) makes most sense. This way we will be able to focus more on concepts instead of trying to figure out IT issues and resolve confusion amongst the participants (and us). Hope that is okay.

**Comment by ayushi-agrawal-gladstone** [comment]
All suggestions were evaluated and incorporated as discussed. Closing the issue.
