### ISSUE TITLE
Intro to R workshop (July 2022) - ideas to consider for next workshop 

### ISSUE THREAD

**Issue by ayushi-agrawal-gladstone** [gladstone-institutes/Bioinformatics-Workshops#3]
1. include the initial demo about read.table in session 1 instead of session 2
2. include more breaks on second day
3. include an objective/goal for the data during demo in session 2
4. have exercises for participants to complete before the workshop (e.g. some starting learnR modules)
5. have more TAs during both sessions
6. dedicated time to solve queries in chat
7. start with smaller dataset in session 2
8. more smaller examples instead of one dataset with no clear aim
9. Explain more how session 2 demo will be helpful in day-to-day work

**Comment by ayushi-agrawal-gladstone** [comment]
@AlexanderPico @MichelaTr I would appreciate your suggestions here. Please feel free to add comments.

**Comment by AlexanderPico** [comment]
I also liked the idea of offering a 30 minute "setup" session either a day before or morning before session 1 to resolve all the trivial issues and initial comfort issues for true beginners students.

But, my favorite in the list is to ask true beginners to complete basic setup and exercises before session 1. This could be coupled with survey responses, i.e., respond with, "you self-identified as a beginner; please do xyz before the workshop and contact us if you run into problems."

**Comment by ayushi-agrawal-gladstone** [comment]
@natalie-23-gill We created a list of ideas based on the feedback for the Intro to R workshop. These might be helpful as you start thinking about the workshop in April.

**Comment by natalie-23-gill** [comment]
Marking as closed and linked in the new issue for this year
