### ISSUE TITLE
Intro to Pathway Analysis (Sept 2022) - Ideas for next workshop

### ISSUE THREAD

**Issue by khanspers** [gladstone-institutes/Bioinformatics-Workshops#4]
- Consider skipping the instruction and hands-on part for data visualization, instead simply showing several (real) examples.
- If we keep data viz, the workshop should be split into two days
- Presentation: Include a lot more general background including about the Gene Ontology, pathway databases.
- Presentation: Include some examples of pathway analysis from literature
- Presentation: reformat the section about drawbacks/caveats to be more clear. Maybe needs more background on how permutations are used etc.

**Comment by khanspers** [comment]
See https://www.youtube.com/watch?v=EhZH2Yl75CA for ideas on other aspects to include.

**Comment by AlexanderPico** [comment]
Add slide near beginning about goal of pathway analysis as an exploratory method. Note how the best pathways to use are those the researcher already knows about, that are relevant to the biology they are studying. _Even if only a few differentially expressed genes overlap and it would never pass an enrichment test, it still might be the most insight pathway analysis result!_ 

Introduce statistical enrichment analysis is a secondary approach to suggest alternative processes that might be relevant. Encourage users to not get bogged down in the p-values; all methods and pathway databases have flaws and there are no "gold standards" to test against. Think of the results as recommended pathways to consider.

**Comment by AlexanderPico** [comment]
What if we made reveal.js tutorials for each of the online tool demos? Some would end in how to open in Cytoscape, other's wouldn't. I think that's fine.

Then in your presentation, you can walk through one example and conclude with a slide pointing to the set of reveal tutorials they can go through on their own at their own pace. One rationale we can give is that if 50 people click "go" at the same time on some of these sites, then they can crash :)

**Comment by khanspers** [comment]
Sounds good. 
[Existing instructions](https://github.com/gladstone-institutes/Bioinformatics-Workshops/blob/master/intro-pathway-analysis-visualization/Hands-on_PathwayAnalysis.pdf) will be converted into two (or more) reveal tutorials.

**Comment by khanspers** [comment]
@AlexanderPico : Do we need a new repo for this, to be able to use reveal.js? Or can we install reveal.js in this repo? 
Alternatively host the new tutorials at tutorials.cytoscape.org.

**Comment by AlexanderPico** [comment]
cytoscape

**Comment by khanspers** [comment]
Tool demo reveal slides are being developed here: https://cytoscape.org/cytoscape-tutorials/protocols/functional-enrichment-analysis

**Comment by AlexanderPico** [comment]
Wow. These are perfect. No edits. Good choice to avoid vertical modules. Those are too confusing for self-guided protocols.

What do you think about adding Interactive Enrichment Analysis too? :D

**Comment by khanspers** [comment]
I can definitely add that! Might still add content to the existing slides for Ernichr/WebGestalt also. 

It's tricky to NOT make the slides be "instructive", like a tutorial. If you come across anything that is more tutorial than demo, let me know.

**Comment by khanspers** [comment]
Slides now include IEA as well. But Im thinking the whole thing is too long now, and maybe should be split into 3 parts? Another option is to provide three links (Enrichr, WebGestalt, IEA) for the first slide in that set. @AlexanderPico What do you think?

https://cytoscape.org/cytoscape-tutorials/protocols/functional-enrichment-analysis

Also still need to add linkouts to Cytoscape tutorials etc.

**Comment by AlexanderPico** [comment]
It's awesome. I'd leave it all in. During a workshop, you can decide to skip one (like WebGestalt) and just tell folks they can go over the other examples on their own. Likewise, you can always skip some detailed slides within a tool section if tight on time.

Like you suggest, maybe the only thing missing is navigation links. These are easy to insert using anchors (see outline slides in our Intro to NetBio presentations). You could make a single outline slide listing the three tools with anchor links and then copy/paste it right before each section, so you can easily skip around when presenting.

**Comment by khanspers** [comment]
"Tour of tools" slides are now complete, I added navigation slides between tools, and updated the example data slides. In the navigation slides I also added a link to a "Downstream Analysis" slide which is at the very end. 
https://cytoscape.org/cytoscape-tutorials/protocols/functional-enrichment-analysis/#/title
