### ISSUE TITLE
Improvements for Intro to R (April 2023)

### ISSUE THREAD

**Issue by natalie-23-gill** [gladstone-institutes/Bioinformatics-Workshops#9]
- [x] Add more examples for each of the basic principles
- [x] Remove the reading in the data part from Part 1
- [x] Add more live coding in part 1
- [x] Add more explanation of the PanTHERIA dataset

Pre-workshop instructions:
- [x] Install tidyverse before the workshop
- [x] Give them an Rscript to run that checks their R version and tidyverse installation (Include screenshots of Rstudio with the instructions)

Overall emphasize the importance of reaching out to us if they have installation issues in the pre-workshop instructions/email.

Related to #3

**Comment by natalie-23-gill** [comment]
- [ ] Add some alternatives for absolute beginners for self-paced learning
- [ ] Update the workshop description to clarify that it might be a little fast-paced for those with absolutely no programming experience

**Comment by reubenthomas** [comment]
I think it would also be helpful to give a little more background about the Pantheria data set in the slides - what is the data of? depending on one's background, it may not be immediately obvious what the terms trophic levels, order, binomial, species etc. are and how they relate to each other. So a couple or two slides may help.

**Comment by natalie-23-gill** [comment]
closed by [3d03689](https://github.com/gladstone-institutes/Bioinformatics-Workshops/commit/3d0368908643a85539c03b8274dcaaef2d2d1252)
